import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Seeding database...");

  // Admin user
  const passwordHash = await bcrypt.hash("admin123", 12);
  await prisma.user.upsert({
    where: { email: "admin@progressestate.com.ua" },
    update: {},
    create: {
      email: "admin@progressestate.com.ua",
      password: passwordHash,
      name: "Адміністратор",
    },
  });
  console.log("✅ Admin user created: admin@progressestate.com.ua / admin123");

  // Sample properties
  const properties = [
    {
      slug: "dvokimnata-kvartira-tsentr-75m2",
      titleUk: "Двокімнатна квартира в центрі, 75 м²",
      titleEn: "2-room apartment in the center, 75 m²",
      descriptionUk: "<p>Чудова квартира в самому серці міста. Просторі кімнати, висока стеля, панорамні вікна з видом на місто. Після якісного ремонту, вся необхідна техніка та меблі включені.</p><p>В пішій доступності — ресторани, кафе, магазини, парк.</p>",
      descriptionEn: "<p>Wonderful apartment in the heart of the city. Spacious rooms, high ceilings, panoramic windows with city view. After quality renovation, all necessary appliances and furniture included.</p>",
      type: "APARTMENT" as const,
      listingType: "SALE" as const,
      price: 2500000,
      currency: "UAH",
      areaSqm: 75,
      rooms: 2,
      bedrooms: 1,
      bathrooms: 1,
      floor: 5,
      totalFloors: 9,
      yearBuilt: 2018,
      city: "Івано-Франківськ",
      district: "center",
      address: "вул. Незалежності, 12",
      latitude: 48.9226,
      longitude: 24.7111,
      features: ["parking", "balcony", "elevator", "furniture", "appliances", "internet"],
      isFeatured: true,
      status: "ACTIVE" as const,
    },
    {
      slug: "trikimnatna-kvartira-pasyichna-95m2",
      titleUk: "Трикімнатна квартира на Пасічній, 95 м²",
      titleEn: "3-room apartment in Pasichna, 95 m²",
      descriptionUk: "<p>Простора квартира в затишному спальному районі. Три повноцінні кімнати, дві ванні кімнати, велика кухня-студія. Новий будинок 2021 року.</p>",
      descriptionEn: "<p>Spacious apartment in a quiet residential area. Three full rooms, two bathrooms, large open kitchen. New building from 2021.</p>",
      type: "APARTMENT" as const,
      listingType: "SALE" as const,
      price: 3200000,
      currency: "UAH",
      areaSqm: 95,
      rooms: 3,
      bedrooms: 2,
      bathrooms: 2,
      floor: 7,
      totalFloors: 12,
      yearBuilt: 2021,
      city: "Івано-Франківськ",
      district: "pasichna",
      address: "вул. Пасічна, 55",
      latitude: 48.9350,
      longitude: 24.7050,
      features: ["parking", "elevator", "new_building", "balcony", "ac"],
      isFeatured: true,
      status: "ACTIVE" as const,
    },
    {
      slug: "odnokimnata-kvartira-bam-42m2",
      titleUk: "Однокімнатна квартира на БАМ, 42 м²",
      titleEn: "1-room apartment in BAM district, 42 m²",
      descriptionUk: "<p>Затишна однокімнатна квартира після ремонту. Тихий двір, розвинена інфраструктура. Ідеально для молодої сім'ї або інвестиції.</p>",
      descriptionEn: "<p>Cozy one-room apartment after renovation. Quiet courtyard, developed infrastructure. Ideal for young family or investment.</p>",
      type: "APARTMENT" as const,
      listingType: "SALE" as const,
      price: 1450000,
      currency: "UAH",
      areaSqm: 42,
      rooms: 1,
      bedrooms: 1,
      bathrooms: 1,
      floor: 3,
      totalFloors: 5,
      yearBuilt: 2010,
      city: "Івано-Франківськ",
      district: "bam",
      features: ["balcony", "internet"],
      isFeatured: false,
      status: "ACTIVE" as const,
    },
    {
      slug: "budynok-prymiski-200m2-10sot",
      titleUk: "Будинок в приміській зоні, 200 м², 10 соток",
      titleEn: "House in suburban area, 200 m², 10 acres",
      descriptionUk: "<p>Просторий двоповерховий будинок з гаражем та великою ділянкою. П'ять кімнат, три ванні, камін у вітальні. Сад з фруктовими деревами.</p>",
      descriptionEn: "<p>Spacious two-story house with garage and large plot. Five rooms, three bathrooms, fireplace in living room. Garden with fruit trees.</p>",
      type: "HOUSE" as const,
      listingType: "SALE" as const,
      price: 6500000,
      currency: "UAH",
      areaSqm: 200,
      landAreaSqm: 1000,
      rooms: 5,
      bedrooms: 4,
      bathrooms: 3,
      floor: 2,
      totalFloors: 2,
      yearBuilt: 2015,
      city: "Івано-Франківськ",
      district: "nova_skvaryava",
      features: ["parking", "garden", "security", "internet", "ac"],
      isFeatured: true,
      status: "ACTIVE" as const,
    },
    {
      slug: "ofisne-prymishchennya-tsentr-120m2",
      titleUk: "Офісне приміщення в центрі, 120 м²",
      titleEn: "Office space in the center, 120 m²",
      descriptionUk: "<p>Представницький офіс у центрі міста. Відкрите планування, переговорна кімната, кімната відпочинку. Висота стелі 3.2 м, велика парковка.</p>",
      descriptionEn: "<p>Representative office in the city center. Open plan, conference room, rest area. Ceiling height 3.2 m, large parking.</p>",
      type: "OFFICE" as const,
      listingType: "RENT" as const,
      price: 45000,
      currency: "UAH",
      areaSqm: 120,
      floor: 2,
      totalFloors: 5,
      city: "Івано-Франківськ",
      district: "center",
      address: "вул. Грушевського, 8",
      features: ["parking", "elevator", "security", "internet", "ac", "open_plan"],
      isFeatured: false,
      status: "ACTIVE" as const,
    },
    {
      slug: "dvokimnata-kvartira-orenida-tsentr-60m2",
      titleUk: "Оренда 2-кімнатної квартири в центрі, 60 м²",
      titleEn: "Rent 2-room apartment in the center, 60 m²",
      descriptionUk: "<p>Чудова квартира для оренди в центрі. Повністю мебльована, вся побутова техніка, інтернет. Поблизу всі зручності.</p>",
      descriptionEn: "<p>Great apartment for rent in the center. Fully furnished, all appliances, internet. All amenities nearby.</p>",
      type: "APARTMENT" as const,
      listingType: "RENT" as const,
      price: 18000,
      currency: "UAH",
      areaSqm: 60,
      rooms: 2,
      bedrooms: 1,
      bathrooms: 1,
      floor: 4,
      totalFloors: 9,
      yearBuilt: 2016,
      city: "Івано-Франківськ",
      district: "center",
      features: ["furniture", "appliances", "internet", "ac", "balcony"],
      isFeatured: true,
      status: "ACTIVE" as const,
    },
    {
      slug: "komertsiyne-prymishchennya-khimik-80m2",
      titleUk: "Комерційне приміщення на Хіміку, 80 м²",
      titleEn: "Commercial premises in Khimik, 80 m²",
      descriptionUk: "<p>Приміщення на першому поверсі житлового будинку. Великі вітрини, окремий вхід, є можливість реконструкції під магазин або кафе.</p>",
      descriptionEn: "<p>Ground floor premises in a residential building. Large windows, separate entrance, possibility of reconstruction into a shop or cafe.</p>",
      type: "COMMERCIAL" as const,
      listingType: "SALE" as const,
      price: 1800000,
      currency: "UAH",
      areaSqm: 80,
      floor: 1,
      totalFloors: 9,
      city: "Івано-Франківськ",
      district: "khimik",
      features: ["parking"],
      isFeatured: false,
      status: "ACTIVE" as const,
    },
    {
      slug: "dilyanky-zemli-pid-zabrudoву-8sot",
      titleUk: "Земельна ділянка під забудову, 8 соток",
      titleEn: "Land plot for construction, 8 acres",
      descriptionUk: "<p>Рівна ділянка в спокійному районі. Всі комунікації підведені. Дозвіл на будівництво наявний.</p>",
      descriptionEn: "<p>Flat plot in a quiet area. All utilities connected. Building permit available.</p>",
      type: "LAND" as const,
      listingType: "SALE" as const,
      price: 850000,
      currency: "UAH",
      areaSqm: 800,
      city: "Івано-Франківськ",
      district: "pasichna",
      features: [],
      isFeatured: false,
      status: "ACTIVE" as const,
    },
    {
      slug: "kvartira-studiya-novobydova-35m2",
      titleUk: "Квартира-студія у новобудові, 35 м²",
      titleEn: "Studio apartment in new building, 35 m²",
      descriptionUk: "<p>Сучасна студія у новому ЖК. Смарт-планування, якісна обробка, панорамне заскління. Чудовий варіант для молодих або під оренду.</p>",
      descriptionEn: "<p>Modern studio in new residential complex. Smart layout, quality finishing, panoramic glazing. Great option for young people or rental.</p>",
      type: "APARTMENT" as const,
      listingType: "SALE" as const,
      price: 1100000,
      currency: "UAH",
      areaSqm: 35,
      rooms: 1,
      bedrooms: 1,
      bathrooms: 1,
      floor: 10,
      totalFloors: 16,
      yearBuilt: 2023,
      city: "Івано-Франківськ",
      district: "bam",
      features: ["elevator", "new_building", "internet", "ac"],
      isFeatured: false,
      status: "ACTIVE" as const,
    },
    {
      slug: "budynok-v-mistsi-130m2-6sot",
      titleUk: "Будинок у місті, 130 м², 6 соток",
      titleEn: "House in the city, 130 m², 6 acres",
      descriptionUk: "<p>Компактний затишний будинок у межах міста. Три кімнати, дві ванні, гараж. Гарний сад, тихий двір.</p>",
      descriptionEn: "<p>Compact cozy house within the city. Three rooms, two bathrooms, garage. Nice garden, quiet courtyard.</p>",
      type: "HOUSE" as const,
      listingType: "SALE" as const,
      price: 4200000,
      currency: "UAH",
      areaSqm: 130,
      landAreaSqm: 600,
      rooms: 3,
      bedrooms: 3,
      bathrooms: 2,
      floor: 2,
      totalFloors: 2,
      yearBuilt: 2012,
      city: "Івано-Франківськ",
      district: "pozytron",
      features: ["parking", "garden", "security"],
      isFeatured: false,
      status: "ACTIVE" as const,
    },
  ];

  for (const prop of properties) {
    await prisma.property.upsert({
      where: { slug: prop.slug },
      update: {},
      create: prop,
    });
  }
  console.log(`✅ ${properties.length} properties seeded`);

  // Testimonials
  const testimonials = [
    {
      authorName: "Олексій Мельник",
      authorRole: "Покупець квартири",
      contentUk: "Чудова команда! Допомогли знайти ідеальну квартиру за два тижні. Все чесно та прозоро, без прихованих комісій.",
      contentEn: "Great team! Helped me find the perfect apartment in two weeks. Everything was honest and transparent, no hidden fees.",
      rating: 5,
      isPublished: true,
      order: 1,
    },
    {
      authorName: "Марія Коваленко",
      authorRole: "Орендар",
      contentUk: "Зверталась щодо оренди офісу. Менеджер підібрав декілька варіантів точно під наші потреби. Рекомендую!",
      contentEn: "I contacted them about renting an office. The manager selected several options exactly to our needs. Highly recommend!",
      rating: 5,
      isPublished: true,
      order: 2,
    },
    {
      authorName: "Іван Петренко",
      authorRole: "Продавець будинку",
      contentUk: "Продали наш будинок швидко та за гарну ціну. Дуже задоволений співпрацею з Progress Estate.",
      contentEn: "Sold our house quickly and at a good price. Very satisfied with the cooperation with Progress Estate.",
      rating: 5,
      isPublished: true,
      order: 3,
    },
  ];

  for (const testimonial of testimonials) {
    await prisma.testimonial.create({ data: testimonial }).catch(() => {});
  }
  console.log("✅ Testimonials seeded");
  console.log("🎉 Seeding complete!");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
